name: urun_siparis
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  another_flushbar: ^1.12.30
  badges: ^3.1.2
  flutter_cart: ^0.0.9
  provider: ^6.1.2
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  path: ^1.8.0
  shared_preferences: ^2.3.2
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/kraker.png
    - images/hamburger.png
    - images/tost.jpg
    - images/icecekler.jpg
    - images/sandwich.jpg
    - images/tavuk_burger.jpg
    - images/kofte_burger.png
    - images/avatar.png
    - images/mentos.png
